pack:
  host:
    selfhost:
      enabled: true
      host: localhost
      port: 1980

  merge-resource-packs:
    packs:
      - BetterModel/build

  font:
    file: font.ttf
    shift: [0, 1]
    size: 9.0
    oversample: 4.0
    #skip: ""

  prompt-message: <white><bold>Neko <yellow>requires resource pack for high-quality gameplay.