pack:
  host:
    selfhost:
      enabled: true
      host: localhost
      port: 1980

  merge-resource-packs:
    packs:
      - BetterModel/build

  prompt-message: <white><bold>Neko <yellow>requires resource pack for high-quality gameplay.